create table students(
 stu_id int primary key,
 stu_email varchar(100),
 stu_password varchar(100),
 stu_fname varchar(100),
 stu_mname varchar(100),
 stu_lname varchar(100),
 stu_dob date,
 stu_gender char,
 stu_blood varchar(10),
 stu_year number,
 stu_division char,
 stu_branch varchar(10),
 stu_add1 longtext,
 stu_add_locality longtext,
 stu_add_city varchar(100),
 stu_add_state varchar(100),
 stu_add_pincode number,
 stu_add_country number,
 stu_father_name varchar(100),
 stu_father_num number,
 stu_father_email varchar(100),
 stu_mother_name varchar(100),
 stu_mother_num number,
 stu_mother_email varchar(100),
 stu_img_path text,
 stu_timestamp timestamp
);